# Generated by Django 4.2.1 on 2023-06-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_staff_leave"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff_leave",
            old_name="date",
            new_name="data",
        ),
    ]
