# Generated by Django 4.2.1 on 2023-07-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_student_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_feedback",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.student"
            ),
        ),
    ]
